/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-hooks/set-state-in-effect */
'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useSettings } from './SettingsContext';

type Language = 'fr';

const translations: Record<string, Record<string, string>> = {
  fr: {
    // Navbar
    home: "Accueil",
    fleet: "Flotte",
    admin: "Dashboard Admin",
    backToWeb: "Retour au Site",
    aboutUs: "À Propos",
    aboutTitle: "Notre Histoire",
    aboutSubtitleText: "LuxeRent propose une sélection incomparable de véhicules de prestige conçue pour rendre vos trajets extraordinaires.",
    aboutStoryTitle: "La Vision LuxeRent",
    aboutStoryText1: "Né d'une passion pour le luxe et l'ingénierie d'exception, LuxeRent est bien plus qu'une agence de location de véhicules. Nous créons des voyages mémorables en proposant une flotte d'élite de voitures de sport, supermotos et jet-skis.",
    aboutStoryText2: "Nos valeurs clés : pas de dépôt de réservation en ligne, la simplicité du paiement sur place, et un service d'assistance personnalisé 24h/24 et 7j/7, pour vous garantir une tranquillité d'esprit absolue.",
    ourLocations: "Nos Agences",
    monacoGarage: "Terminal Aéroport d'Alger",
    monacoGarageAddress: "Terminal 2, Aéroport International Houari Boumédiène, Alger",
    niceAirport: "Agence Centrale d'Oran",
    niceAirportAddress: "Boulevard Emir Abdelkader, Centre Ville, Oran",
    operatingHours: "Heures d'Ouverture",
    operatingHoursVal: "Lundi - Dimanche : 08:00 - 22:00",
    contactUs: "Contactez-Nous",
    fullName: "Nom Complet",
    emailAddress: "Adresse E-mail",
    subject: "Sujet",
    message: "Votre Message",
    selectSubject: "Sélectionnez un sujet",
    generalInquiry: "Demande Générale",
    partnership: "Partenariat Commercial",
    vipRequest: "Réservation Personnalisée VIP",
    submitMessage: "Envoyer le Message",
    sending: "Envoi en cours...",
    messageSent: "Message envoyé avec succès !",
    messageSentDesc: "Nous vous recontacterons dans les 2 prochaines heures.",
    ourStoryTag: "Notre Histoire",
    ourLocationsSubtitle: "Récupérez vos véhicules en toute simplicité dans nos agences de prestige.",
    completeTrustTitle: "Confiance Totale",
    completeTrustDesc: "Zéro caution, paiement sur place transparent",
    premiumQualityTitle: "Qualité Premium",
    premiumQualityDesc: "Flotte de luxe soigneusement révisée et nettoyée",
    totalFlexibilityTitle: "Flexibilité Totale",
    totalFlexibilityDesc: "Annulations gratuites et assistance 24h/24",
    flexibleHoursTitle: "Horaires Flexibles",
    flexibleHoursDesc: "Service de prise en charge tôt ou tard",
    contactUsSubtitle: "Une question, un partenariat ou une demande personnalisée ? Écrivez-nous.",
    newMessage: "Nouveau message",
    howCanWeHelp: "Comment pouvons-nous vous aider ?",
    addressLabel: "Adresse",
    phoneFieldLabel: "Téléphone",
    emailFieldLabel: "E-mail",
    mapView: "Itinéraire",
    noLocationsConfigured: "Aucune agence configurée.",

    // Homepage Hero
    heroBadge: "Disponible dès maintenant : Collection 2026",
    heroTitle1: "Le frisson de la",
    heroTitle2: "location premium",
    heroSubtitle: "Faites votre choix parmi notre flotte exclusive de voitures, motos et jet-skis. Payez facilement sur place à la récupération de votre véhicule.",
    pickupLocation: "Lieu de prise en charge",
    rentalDates: "Dates & Heures de location",
    searchFleet: "Rechercher",
    selectLocation: "Sélectionnez un emplacement",
    vehiclesStat: "Véhicules",
    satisfactionStat: "Avis clients",
    categoriesStat: "Catégories",
    supportStat: "Support 24/7",
    pickupLocationError: "Veuillez sélectionner un lieu de prise en charge",
    returnDateError: "La date et l'heure de retour doivent être après la date et l'heure de prise en charge",
    yourNameLabel: "Votre nom",
    confirmReservation: "Confirmer la réservation",

    // Vitrine sections
    browseCategories: "Catégories de Flotte",
    discoverFleet: "Découvrez notre sélection exclusive",
    featuredVehicles: "Collection Premium",
    exploreFavorites: "Découvrez les coups de cœur de nos clients",
    viewAllFleet: "Voir toute la flotte",
    quickReserve: "Réserver",
    payLater: "Payer Plus Tard",
    whyChooseUs: "Pourquoi Choisir LuxeRent ?",
    qualityService: "Qualité & Service Premium",
    qualityServiceDesc: "Tous nos véhicules subissent des contrôles de qualité rigoureux pour garantir sécurité et tranquillité d'esprit.",
    payOnSite: "Paiement Sur Place",
    payOnSiteDesc: "Zéro frais initiaux. Payez en toute sécurité lors de la récupération du véhicule dans notre agence.",
    topPerformance: "Performance Maximale",
    topPerformanceDesc: "Entretien régulier et nettoyage minutieux pour garder les moteurs vifs et les carrosseries étincelantes.",
    premiumSupport: "Support Premium 24/7",
    premiumSupportDesc: "Nous sommes toujours prêts à vous assister à tout moment de votre voyage.",
    cars: "Voitures",
    motorcycles: "Motos",
    jetskis: "Jet Skis",

    // Fleet page
    ourFleet: "Notre Flotte Premium",
    fleetSubtitle: "Sélectionnez le véhicule idéal pour votre prochaine aventure.",
    filters: "Filtres",
    maxPrice: "Prix Max",
    transmission: "Transmission",
    fuelType: "Carburant",
    clearFilters: "Effacer les filtres",
    showingAll: "Affichage de tous les résultats",
    activeFilters: "Filtres Actifs :",
    clearAll: "Tout effacer",
    noVehiclesMatch: "Aucun véhicule ne correspond",
    resetFiltersDesc: "Essayez de modifier vos filtres pour trouver le véhicule idéal.",
    resetAllFilters: "Réinitialiser les filtres",
    reserveNow: "Réserver",

    // Detail page
    specifications: "Spécifications",
    whyRentWithUs: "Pourquoi réserver chez nous ?",
    excellentCondition: "Excellent État",
    excellentConditionDesc: "Tous nos véhicules sont régulièrement entretenus et vérifiés avant chaque location pour votre sécurité.",
    payOnSiteTitle: "Paiement Sur Place",
    payOnSiteDetail: "Pas de carte de crédit requise en ligne. Payez en toute sécurité lors de la prise en charge dans notre agence.",
    reservePayLater: "Réserver maintenant (Paiement sur place)",
    secureBooking: "Réservation sécurisée. Zéro coût initial.",

    // Checkout page
    bookingSummary: "Résumé de Réservation",
    continueAddons: "Continuer vers les options",
    enhanceTrip: "Optimisez votre voyage",
    enhanceYourTrip: "Personnalisez votre voyage",
    freeCancellation: "Annulation Gratuite",
    freeCancellationDesc: "Annulez gratuitement à tout moment. Aucun paiement en ligne requis aujourd'hui.",
    continueDetails: "Continuer vers vos détails",
    driverInfo: "Informations Conducteur",
    phoneNumber: "Numéro de téléphone",
    docVerification: "Vérification des Documents",
    verificationDetail: "Veuillez noter que vous devrez présenter votre permis de conduire et une pièce d'identité valides lors de la prise en charge.",
    clickUpload: "Cliquez pour charger les documents (Optionnel)",
    completeReservation: "Finaliser la réservation",
    reservationConfirmed: "Réservation Confirmée !",
    bookingSecured: "Votre réservation a été validée avec succès. Veuillez apporter votre permis de conduire et votre moyen de paiement au lieu de prise en charge.",
    backToHome: "Retour à l'Accueil",
    priceDetails: "Détails du Prix",
    rentalPrice: "Prix de Location",
    baseCost: "Coût de Base",
    addOns: "Options additionnelles",
    totalPrice: "Prix Total",
    payablePickup: "À régler sur place",
    luxeGuarantee: "Garantie LuxeRent",
    luxeGuaranteeDesc: "Pas d'acompte requis. Annulez gratuitement à tout moment avant la prise en charge du véhicule.",
    summary: "Résumé",
    details: "Détails",
    confirm: "Confirmation",

    // Admin page
    adminPortal: "Portail Administrateur",
    enterPasscode: "Veuillez saisir le code d'accès pour accéder au tableau de bord.",
    verifyPasscode: "Valider l'Accès",
    passcodePlaceholder: "Code secret admin",
    wrongPasscode: "Code incorrect. Veuillez réessayer.",
    bookingLogs: "Réservations Clients",
    fleetManager: "Gestion de Flotte",
    addVehicle: "Ajouter un véhicule",
    editVehicle: "Modifier le véhicule",
    totalBookings: "Total Réservations",
    activeClients: "Clients Actifs",
    pendingApprovals: "En attente d'approbation",
    recentReservations: "Réservations Récentes",
    make: "Marque",
    model: "Modèle",
    year: "Année",
    pricePerDay: "Prix par Jour (DA)",
    pricePerHour: "Prix par Heure (DA)",
    category: "Catégorie",
    imageUrl: "URL de l'image",
    doors: "Portes",
    cc: "Cylindrée (cc)",
    horsepower: "Chevaux (ch)",
    features: "Caractéristiques",
    save: "Enregistrer les modifications",
    cancel: "Annuler",
    deleteConfirm: "Êtes-vous sûr de vouloir supprimer ce véhicule ?",
    dashboard: "Tableau de Bord",
    categories: "Catégories",
    messages: "Messages",
    settings: "Paramètres",
    refresh: "Rafraîchir",
    seedData: "Données de Test",
    seeding: "Génération...",
    logout: "Déconnexion",
    newBooking: "Nouvelle Réservation",
    newReservation: "Nouvelle Réservation",
    guestInformation: "Informations Client",
    fullNameLabel: "Nom Complet *",
    phoneLabel: "Téléphone *",
    emailLabel: "E-mail *",
    vehicleAndSchedule: "Véhicule & Calendrier",
    vehicleLabel: "Véhicule *",
    pickupDateTime: "Date & Heure de Départ *",
    returnDateTime: "Date & Heure de Retour *",
    pickupLocationLabel: "Lieu de Départ *",
    rentalDurationType: "Type de durée *",
    createBooking: "Créer la Réservation",
    creating: "Création...",
    pricingTiersAndDiscounts: "Tarifs & Réductions",
    pricePerHourLabel: "Prix par Heure (DA)",
    pricePerHalfDayLabel: "Prix par Demi-Journée (12h) (DA)",
    pricePerDayLabel: "Prix par Jour (24h) (DA)",
    discountPercentageLabel: "Pourcentage de Réduction (%)",
    discountLabel: "Nom de la Promo",
    description: "Description",
    requirements: "Conditions Requises",
    conditions: "Conditions d'Utilisation",
    hourly: "À l'heure",
    halfDay: "Demi-journée (12h)",
    daily: "Par jour (24h)",
    revenueBookingsTrend: "Tendance des Revenus & Réservations",
    monthlyOverview: "Aperçu mensuel des performances de la plateforme",
    stableGrowth: "Croissance Stable",
    adminSubtitle: "Gérez votre flotte premium et les réservations de vos clients.",
    guestDetails: "Détails du Client",
    vehicle: "Véhicule",
    schedule: "Calendrier",
    location: "Lieu",
    total: "Total",
    status: "Statut",
    loadingReservations: "Chargement des réservations...",
    noBookingsFound: "Aucune réservation trouvée.",
    loadingFleet: "Chargement de la flotte...",
    emptyFleet: "Flotte Vide",
    noVehiclesAdded: "Aucun véhicule n'a encore été ajouté.",
    standard: "Standard",
    doorsLabel: "Portes",
    perDay: "jour",
    perHr: "heure",
    subcategoryLabel: "Sous-catégorie",
    none: "Aucun",
    disableHint: "(0 pour désactiver)",
    noDiscountHint: "(0 pour aucune réduction)",
    descriptionPlaceholder: "Description du véhicule",
    requirementsPlaceholder: "Ex : Permis de conduire valide, 21 ans et plus",
    conditionsPlaceholder: "Ex : Non fumeur, Retour avec le plein",
    landingImageLabel: "Image de présentation (Section Description)",
    clickDragUpload: "Cliquez ou glissez pour charger l'image de présentation",
    blockedDates: "Dates Bloquées",
    startDate: "Date de Début",
    endDate: "Date de Fin",
    add: "Ajouter",
    vehiclePhoto: "Photo du véhicule",
    imageUploaded: "Image chargée",
    changeImage: "Changer d'image",
    uploadVehiclePhoto: "Télécharger une photo de véhicule",
    recommendedFormats: "Format recommandé : PNG, JPG, JPEG ou WEBP",
    selectVehicle: "Sélectionner un véhicule",
    rentalDurationTypeLabel: "Type de durée *",
    hour: "Heure",
    halfDayLabel: "Demi-journée (12h)",
    dayLabel: "Jour (24h)",
    pickupLocationPlaceholder: "Ex : Aéroport d'Alger",
    uploadFailed: "Échec du téléchargement",
    invalidUploadResponse: "Réponse invalide du serveur",
    uploadError: "Erreur lors du téléchargement",
    loginFailed: "Échec de la connexion",
    networkError: "Erreur réseau. Veuillez vérifier votre connexion.",
    seedSuccess: "Base de test générée avec succès !",
    seedNonJson: "Base générée, mais réponse non-JSON du serveur.",
    seedFailed: "Échec de la génération de la base de test.",
    statusUpdateFailed: "Échec de la mise à jour du statut",
    statusUpdateError: "Erreur lors de la mise à jour du statut",
    saveVehicleFailed: "Échec de l'enregistrement du véhicule",
    saveVehicleError: "Erreur lors de l'enregistrement du véhicule",
    deleteVehicleFailed: "Échec de la suppression du véhicule",
    deleteVehicleError: "Erreur lors de la suppression du véhicule",
    createBookingFailed: "Échec de la création de la réservation",
    createBookingError: "Erreur lors de la création de la réservation",
    pending: "En attente",
    confirmed: "Confirmé",
    completed: "Terminé",
    cancelled: "Annulé",
    available: "Disponible",
    rented: "Loué",
    maintenance: "Maintenance",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    authenticate: "S'authentifier",
    settingsSaved: "Paramètres sauvegardés avec succès !",
    settingsSaveFailed: "Échec de la sauvegarde des paramètres.",
    settingsSaveError: "Erreur lors de la sauvegarde des paramètres.",
    uploadImageFailed: "Échec du chargement de l'image.",
    cmsAndSettings: "CMS & Paramètres",
    showDateSearchLabel: "Afficher la recherche par date sur la page d'accueil",
    saveChanges: "Enregistrer les modifications",
    saving: "Enregistrement...",
    homePageHero: "Bannière Page d'Accueil",
    backgroundImage: "Image d'arrière-plan",
    clickUploadNewImage: "Cliquez pour charger une nouvelle image",
    pickupLocations: "Lieux de prise en charge",
    locationName: "Nom du lieu",
    locationPlaceholder: "Ex : Aéroport d'Alger",
    locationType: "Type",
    airport: "Aéroport",
    cityCenter: "Centre-ville",
    marinaBeach: "Port / Plage",
    vehicleCategories: "Catégories de véhicules",
    inboxMessages: "Boîte de réception",
    unread: "non lu(s)",
    noMessages: "Aucun message",
    noContactRequests: "Il n'y a pas encore de demandes de contact.",
    deleteMessageConfirm: "Supprimer ce message ?",
    from: "De",
    date: "Date",
    markRead: "Marquer Lu",
    markUnread: "Marquer Non Lu",
    delete: "Supprimer",
    failedToggleVisibility: "Échec du basculement de la visibilité",
    deleteCategoryConfirm: "Êtes-vous sûr de vouloir supprimer cette catégorie ? Cela peut affecter les véhicules existants.",
    failedDeleteCategory: "Échec de la suppression de la catégorie",
    categoryNameRequired: "Le nom de la catégorie est requis",
    failedSaveCategory: "Échec de l'enregistrement de la catégorie",
    failedCreateCategory: "Échec de la création de la catégorie",
    addCategory: "Ajouter une catégorie",
    newCategoryName: "Nom de la nouvelle catégorie",
    categoryPlaceholder: "Ex : SUV, Yacht...",
    categoryName: "Nom de la catégorie",
    subcategories: "Sous-catégories",
    noSubcategories: "Aucune sous-catégorie pour le moment.",
    addSubcategoryPlaceholder: "Ajouter une sous-catégorie...",
    visible: "Visible",
    hidden: "Masqué",
    clientsDatabase: "Base de données clients",
    exportExcel: "Exporter vers Excel",
    totalSpent: "Total dépensé",
    lastRental: "Dernière location",
    active: "Actif",
    inactive: "Inactif",
    totalSpentLabel: "Total dépensé (DA)",
    lastRentalDateLabel: "Date de dernière location",
    noClientsFound: "Aucun client trouvé.",
    editBooking: "Modifier la réservation",
    editReservation: "Modifier la réservation",
    updateBooking: "Mettre à jour",
    updating: "Mise à jour...",
    updateBookingFailed: "Échec de la mise à jour de la réservation",
    updateBookingError: "Erreur lors de la mise à jour de la réservation",
    viewMode: "Mode d'affichage",
    tableView: "Tableau",
    gridView: "Grille",
    // Custom keys
    allVehicles: "Toute la Flotte",
    aboutThisVehicle: "À propos de ce véhicule",
    rentalRequirements: "Conditions de Location",
    conditionsLabel: "Conditions d'Utilisation",
    unavailableDatesLabel: "Dates d'Indisponibilité :",
    editionLabel: "Édition",
    toWord: "à",
    todayPreset: "Aujourd'hui",
    tomorrowPreset: "Demain",
    weekendPreset: "Ce Week-end",
    nextWeekPreset: "Sem. Prochaine",
    transmissionLabel: "Transmission",
    fuelLabel: "Carburant",
    ccLabel: "Cylindrée (cc)",
    horsepowerLabel: "Puissance (ch)",
    helmetIncludedLabel: "Casque Inclus",
    lifeJacketsIncludedLabel: "Gilets de Sauvetage",
    automatic: "Automatique",
    manual: "Manuelle",
    petrol: "Essence",
    diesel: "Diesel",
    electric: "Électrique",
    hybrid: "Hybride",
    yes: "Oui",
    no: "Non",
    summaryStep: "Résumé",
    addonsStep: "Options",
    detailsStep: "Détails",
    confirmStep: "Confirmé",
    backToVehicle: "Retour au véhicule",
    estimatedTotal: "Total estimé",
    yourInformation: "Vos informations",
    driverNameLabel: "Nom complet",
    driverNamePlaceholder: "Votre nom complet",
    fullNamePlaceholder: "Votre nom complet",
    payOnPickupDesc: "Paiement sur place — Aucun frais maintenant",
    processing: "Traitement...",
    confirmBooking: "Confirmer ma réservation",
    rateLabel: "Tarif",
    durationLabel: "Durée",
    baseRentalLabel: "Location de base",
    quickReservation: "Réservation Rapide",
    selectPickupLocation: "Veuillez sélectionner un lieu de prise en charge",
    returnDateAfterPickup: "La date de retour doit être après la date de départ",
    bookingSuccess: "Réservation réussie ! Nous vous contacterons sous peu.",
    premiumSelection: "Sélection Premium",
    flatRateTrip: "Frais fixes pour tout le séjour",
    pricedPerUnit: "Prix par unité de temps",
    pricedPerDurationUnit: "Prix par unité de temps",
    free: "Gratuit",
    noAddonsAvailable: "Aucune option supplémentaire disponible pour ce véhicule.",
    secureBookingInfo: "Réservation sécurisée",
    payOnPickupInfo: "Paiement sur place",
    dataSafeProtected: "Données sécurisées et protégées",
    allSet: "C'est tout bon !",
    hoursCountUnit: "heures",
    hourCountUnit: "heure",
    halfDaysCountUnit: "demi-journées",
    halfDayCountUnit: "demi-journée",
    daysCountUnit: "jours",
    dayCountUnit: "jour",
    car: "Voiture",
    motorcycle: "Moto",
    jetski: "Jet Ski",
    securityDepositLabel: "Caution (Dépôt de Garantie)",
    cautionOptionalTitle: "Dépôt de Garantie (Caution)",
    cautionOptionalDesc: "Entièrement remboursable au retour du véhicule en bon état",
    optional: "Choix Optionnel",
    payOnPickup: "Gérer la caution sur place à l'agence",
    standardCautionNotice: "Régler le dépôt directement lors de la récupération",
    includeCautionInBooking: "Enregistrer la caution dans la réservation",
    refundable: "Remboursable",
    cautionRegistered: "Caution enregistrée",
    cautionPayableOnSite: "Caution payable sur place",
    cautionRequired: "Dépôt de caution facultatif selon formule",
    rentalRules: "Règlement & Conditions de location",
    cautionRefundableDesc: "Entièrement remboursable au retour du véhicule en bon état.",
    driverQuestion: "Besoin d'un chauffeur professionnel ?",
    driverPrompt: "Chauffeur professionnel",
    selfDrive: "Sans Chauffeur (Conduite libre)",
    withChauffeur: "Avec Chauffeur",
    driverPriceInfo: "louez un chauffeur local pour naviguer facilement dans le trafic",
    driverOptionLabel: "Service Chauffeur",
    driverEnabled: "Service Chauffeur Disponible",
    driverDisabled: "Conduite Libre Uniquement",
    editVehicleTranslations: "Gérer les Traductions",
    requirementsFr: "Conditions (Français)",
    requirementsAr: "Conditions (Arabe)",
    conditionsFr: "Conditions (Français)",
    conditionsAr: "Conditions (Arabe)",
    descriptionFr: "Description (Français)",
    descriptionAr: "Description (Arabe)",
    extraOptionsTitle: "Options & Équipements Supplémentaires",
    extraOptionsSubtitle: "Gérez les équipements louables comme le GPS, les casques ou sièges bébé.",
    addNewOption: "Ajouter une option",
    optionName: "Nom de l'option",
    price: "Prix",
    bindingRule: "Règle d'attribution",
    actions: "Actions",
    globalAll: "Global (Tous véhicules)",
    categoryRule: "Catégorie spécifique",
    vehicleRule: "Véhicule spécifique",
    flatRateLabel: "Tarif Fixe (Par séjour)",
    pricedPerDay: "Par Jour / Unité",
    editOption: "Modifier l'option",
    newExtraOption: "Nouvelle option supplémentaire",
    optionNameEn: "Nom de l'option (Anglais)",
    nameFr: "Nom (Français)",
    nameAr: "Nom (Arabe)",
    priceDa: "Prix (DA)",
    priceType: "Type de tarification",
    adminSelectCategory: "Sélectionnez la catégorie",
    adminSelectVehicle: "Sélectionnez le véhicule",
    chooseVehicle: "-- Choisir un véhicule --",
    saveOption: "Enregistrer l'option",
    noExtraOptionsFound: "Aucune option supplémentaire trouvée",
    loadingOptions: "Chargement des options...",
    extraOptions: "Options & Équipements",
    revenueTrendTitle: "Tendance des Revenus & Réservations",
    revenueTrendSubtitle: "Aperçu mensuel des performances de la plateforme",
    generalSettings: "Paramètres Généraux",
    heroAndBranding: "Héros & Image de marque",
    aboutUsTab: "À Propos (Notre Histoire)",
    agencyLocationsTab: "Agences",
    generalConfiguration: "Configuration Générale",
    storeName: "Nom de l'Agence",
    globalAgencyPhone: "Téléphone Principal",
    globalAgencyEmail: "Email Principal",
    globalAgencyAddress: "Adresse Principale",
    storeLogo: "Logo de l'Agence",
    removeLogo: "Supprimer le logo",
    brandColors: "Couleurs de la marque",
    preview: "Aperçu",
    primaryColor: "Couleur Principale",
    secondaryColor: "Couleur Secondaire",
    showSearchWidget: "Afficher le bloc de recherche",
    showSearchWidgetDesc: "Activer ou désactiver complètement le bloc de recherche sur la page d'accueil."
  }
};

type LanguageContextType = {
  locale: Language;
  setLocale: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  formatCurrency: (amount: number) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const locale: Language = 'fr';

  useEffect(() => {
    document.documentElement.dir = 'ltr';
    document.documentElement.lang = 'fr';
  }, []);

  const setLocale = () => {};

  const { settings } = useSettings();

  const t = (key: string, fallback?: string): string => {
    const found = translations.fr?.[key];
    const text = found !== undefined ? found : (fallback !== undefined ? fallback : key);
    if (settings?.storeName && typeof text === 'string') {
      return text.replace(/LuxeRent/g, settings.storeName);
    }
    return text;
  };

  const formatCurrency = (amount: number): string => {
    const formatted = amount.toLocaleString('fr-DZ');
    return `${formatted} DA`;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
