/* eslint-disable react-hooks/exhaustive-deps */
/* eslint-disable react-hooks/set-state-in-effect */
'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useSettings } from './SettingsContext';

type Language = 'fr' | 'en' | 'ar';

const translations: Record<string, Record<string, string>> = {
  fr: {
    // Navbar
    home: "Home",
    fleet: "Our Fleet",
    admin: "Admin Dashboard",
    backToWeb: "Back to Website",
    aboutUs: "About Us",
    aboutTitle: "Our Story",
    aboutSubtitleText: "LuxeRent offers an incomparable selection of prestige vehicles designed to make your journey extraordinary.",
    aboutStoryTitle: "The LuxeRent Vision",
    aboutStoryText1: "Founded with a passion for luxury and exceptional engineering, LuxeRent is more than a vehicle rental company. We are purveyors of unforgettable journeys, offering an elite fleet of sports cars, superbikes, and jet skis.",
    aboutStoryText2: "Our simple core values: zero upfront booking deposits, transparent pay-on-site convenience, and 24/7 personalized customer care ensure you enjoy complete peace of mind while cruising through magnificent destinations.",
    ourLocations: "Our Pickup Locations",
    monacoGarage: "Algiers Airport Terminal",
    monacoGarageAddress: "Terminal 2, Houari Boumédiène International Airport, Algiers",
    niceAirport: "Oran Central Agency",
    niceAirportAddress: "Boulevard Emir Abdelkader, Downtown, Oran",
    operatingHours: "Operating Hours",
    operatingHoursVal: "Monday - Sunday: 08:00 AM - 10:00 PM",
    contactUs: "Contact Us",
    fullName: "Full Name",
    emailAddress: "Email Address",
    subject: "Subject",
    message: "Message",
    selectSubject: "Select a subject",
    generalInquiry: "General Inquiry",
    partnership: "Business Partnership",
    vipRequest: "VIP Custom Booking",
    submitMessage: "Send Message",
    sending: "Sending...",
    messageSent: "Message sent successfully!",
    messageSentDesc: "We will contact you within the next 2 hours.",
    ourStoryTag: "Our Story",
    ourLocationsSubtitle: "Seamlessly pick up your elite vehicles from our premium agency locations.",
    completeTrustTitle: "Complete Trust",
    completeTrustDesc: "Zero upfront deposits, transparent on-site payments",
    premiumQualityTitle: "Premium Quality",
    premiumQualityDesc: "Meticulously inspected, spotless elite fleet",
    totalFlexibilityTitle: "Total Flexibility",
    totalFlexibilityDesc: "Free cancellations and round-the-clock support",
    flexibleHoursTitle: "Flexible Hours",
    flexibleHoursDesc: "Early morning and late night pick-ups available",
    contactUsSubtitle: "Have a question, partnership, or custom VIP request? Write to us.",
    newMessage: "New Message",
    howCanWeHelp: "How can we help you?",
    addressLabel: "Address",
    phoneFieldLabel: "Phone",
    emailFieldLabel: "Email",
    mapView: "Map View",
    noLocationsConfigured: "No locations configured.",

    // Homepage Hero
    heroBadge: "Now Available: 2024 Collection",
    heroTitle1: "The thrill of",
    heroTitle2: "premium rentals",
    heroSubtitle: "Choose from our exclusive fleet of cars, motorcycles, and jet skis. Pay easily on-site when you pick up your vehicle.",
    pickupLocation: "Pickup Location",
    rentalDates: "Rental Dates & Times",
    searchFleet: "Search Fleet",
    selectLocation: "Select a location",
    vehiclesStat: "Vehicles",
    satisfactionStat: "Client rating",
    categoriesStat: "Categories",
    supportStat: "Support",
    pickupLocationError: "Please select a pickup location",
    returnDateError: "Return date & time must be after pickup date & time",
    yourNameLabel: "Your Name",
    confirmReservation: "Confirm Reservation",

    // Vitrine sections
    browseCategories: "Browse Categories",
    discoverFleet: "Discover our exclusive selection",
    featuredVehicles: "Premium Collection",
    exploreFavorites: "Explore our customer favorites",
    viewAllFleet: "View Full Fleet",
    quickReserve: "Quick Reserve",
    payLater: "Pay Later",
    whyChooseUs: "Why Choose LuxeRent?",
    qualityService: "Premium Quality & Service",
    qualityServiceDesc: "All our vehicles go through rigorous quality checks to deliver safety and peace of mind.",
    payOnSite: "Pay On-Site",
    payOnSiteDesc: "Zero upfront cost. Pay securely when picking up the vehicle at our agency.",
    topPerformance: "Top Performance",
    topPerformanceDesc: "Regular checkups and detailing to keep the engines purring and bodies spotless.",
    premiumSupport: "24/7 Premium Support",
    premiumSupportDesc: "Always ready to assist you during your rental journey whenever you need us.",
    cars: "Cars",
    motorcycles: "Motorcycles",
    jetskis: "Jet Skis",

    // Fleet page
    ourFleet: "Our Premium Fleet",
    fleetSubtitle: "Select the perfect vehicle for your next adventure.",
    filters: "Filters",
    maxPrice: "Max Price",
    transmission: "Transmission",
    fuelType: "Fuel Type",
    clearFilters: "Clear Filters",
    showingAll: "Showing all results",
    activeFilters: "Active Filters:",
    clearAll: "Clear All",
    noVehiclesMatch: "No vehicles match filters",
    resetFiltersDesc: "Try resetting some filters to find your perfect vehicle.",
    resetAllFilters: "Reset All Filters",
    reserveNow: "Reserve Now",

    // Detail page
    specifications: "Specifications",
    whyRentWithUs: "Why rent with us?",
    excellentCondition: "Excellent Condition",
    excellentConditionDesc: "All vehicles are regularly maintained and checked before every rental to ensure safety.",
    payOnSiteTitle: "Pay On-Site",
    payOnSiteDetail: "No credit card required online. Pay securely when you pick up the vehicle at our location.",
    reservePayLater: "Reserve Now (Pay Later)",
    secureBooking: "Secure booking. Zero upfront cost.",

    // Checkout page
    bookingSummary: "Booking Summary",
    continueAddons: "Continue to Add-ons",
    enhanceTrip: "Enhance your trip",
    enhanceYourTrip: "Enhance Your Trip",
    freeCancellation: "Free Cancellation",
    freeCancellationDesc: "Cancel for free anytime. No online payment required today.",
    continueDetails: "Continue to Details",
    driverInfo: "Driver Information",
    phoneNumber: "Phone Number",
    docVerification: "Document Verification",
    verificationDetail: "Please note that you will need to present your valid Driving License and ID upon pickup.",
    clickUpload: "Click to upload documents (Optional)",
    completeReservation: "Complete Reservation",
    reservationConfirmed: "Reservation Confirmed!",
    bookingSecured: "Your booking has been secured successfully. Please bring your driving license and payment method to the pick-up location.",
    backToHome: "Back to Home",
    priceDetails: "Price Details",
    rentalPrice: "Rental Price",
    baseCost: "Base Cost",
    addOns: "Add-ons",
    totalPrice: "Total Price",
    payablePickup: "Payable at pick-up",
    luxeGuarantee: "LuxeRent Guarantee",
    luxeGuaranteeDesc: "No upfront deposit. Cancel anytime before pick-up with zero cancellation fees.",
    summary: "Summary",
    details: "Details",
    confirm: "Confirm",

    // Admin page
    adminPortal: "Admin Portal",
    enterPasscode: "Please enter security passcode to access dashboard.",
    verifyPasscode: "Verify Passcode",
    passcodePlaceholder: "Enter admin passcode",
    wrongPasscode: "Incorrect passcode. Please try again.",
    bookingLogs: "Booking Logs",
    fleetManager: "Fleet Manager",
    addVehicle: "Add Vehicle",
    editVehicle: "Edit Vehicle",
    totalBookings: "Total Bookings",
    activeClients: "Active Clients",
    pendingApprovals: "Pending Approvals",
    recentReservations: "Recent Reservations",
    make: "Make",
    model: "Model",
    year: "Year",
    pricePerDay: "Price Per Day (DA)",
    pricePerHour: "Price Per Hour (DA)",
    category: "Category",
    imageUrl: "Image URL",
    doors: "Doors",
    cc: "Engine Size (cc)",
    horsepower: "Horsepower",
    features: "Features",
    save: "Save Details",
    cancel: "Cancel",
    deleteConfirm: "Are you sure you want to delete this vehicle?",
    dashboard: "Dashboard",
    categories: "Categories",
    messages: "Messages",
    settings: "Settings",
    refresh: "Refresh",
    seedData: "Seed Data",
    seeding: "Seeding...",
    logout: "Logout",
    newBooking: "New Booking",
    newReservation: "New Reservation",
    guestInformation: "Guest Information",
    fullNameLabel: "Full Name *",
    phoneLabel: "Phone *",
    emailLabel: "Email *",
    vehicleAndSchedule: "Vehicle & Schedule",
    vehicleLabel: "Vehicle *",
    pickupDateTime: "Pickup Date & Time *",
    returnDateTime: "Return Date & Time *",
    pickupLocationLabel: "Pickup Location *",
    rentalDurationType: "Rental Duration Type *",
    createBooking: "Create Booking",
    creating: "Creating...",
    pricingTiersAndDiscounts: "Pricing Tiers & Discounts",
    pricePerHourLabel: "Price per Hour (DA)",
    pricePerHalfDayLabel: "Price per Half-Day (12h) (DA)",
    pricePerDayLabel: "Price per Day (24h) (DA)",
    discountPercentageLabel: "Discount Percentage (%)",
    discountLabel: "Discount Label",
    description: "Description",
    requirements: "Requirements",
    conditions: "Conditions",
    hourly: "Hourly",
    halfDay: "Half Day (12h)",
    daily: "Daily (24h)",
    revenueBookingsTrend: "Revenue & Bookings Trend",
    monthlyOverview: "Monthly overview of platform performance",
    stableGrowth: "Stable Growth",
    adminSubtitle: "Manage your premium fleet and incoming client reservations.",
    guestDetails: "Guest Details",
    vehicle: "Vehicle",
    schedule: "Schedule",
    location: "Location",
    total: "Total",
    status: "Status",
    loadingReservations: "Loading reservations...",
    noBookingsFound: "No bookings found.",
    loadingFleet: "Loading Fleet...",
    emptyFleet: "Empty Fleet",
    noVehiclesAdded: "No vehicles have been added yet.",
    standard: "Standard",
    doorsLabel: "Doors",
    perDay: "day",
    perHr: "hr",
    subcategoryLabel: "Subcategory",
    none: "None",
    disableHint: "(0 to disable)",
    noDiscountHint: "(0 for no discount)",
    descriptionPlaceholder: "Vehicle description (supports text)",
    requirementsPlaceholder: "e.g. Valid Driver's License, 21+ Years Old",
    conditionsPlaceholder: "e.g. No smoking, Return with full tank",
    landingImageLabel: "Landing Image (For Description section)",
    clickDragUpload: "Click or drag to upload landing image",
    blockedDates: "Blocked Dates",
    startDate: "Start Date",
    endDate: "End Date",
    add: "Add",
    vehiclePhoto: "Vehicle Photo",
    imageUploaded: "Image Uploaded",
    changeImage: "Change Image",
    uploadVehiclePhoto: "Upload Vehicle Photo",
    recommendedFormats: "Recommended: PNG, JPG, JPEG, or WEBP",
    selectVehicle: "Select a vehicle",
    rentalDurationTypeLabel: "Rental Duration Type *",
    hour: "Hour",
    halfDayLabel: "Half Day (12h)",
    dayLabel: "Day (24h)",
    pickupLocationPlaceholder: "e.g. Aéroport d'Alger",
    uploadFailed: "Upload failed",
    invalidUploadResponse: "Invalid response from upload server",
    uploadError: "Error uploading file",
    loginFailed: "Login failed",
    networkError: "Network error. Please check your connection.",
    seedSuccess: "Seed completed successfully!",
    seedNonJson: "Database seeded, but received non-JSON response from server.",
    seedFailed: "Failed to seed database.",
    statusUpdateFailed: "Failed to update status",
    statusUpdateError: "Error updating status",
    saveVehicleFailed: "Failed to save vehicle",
    saveVehicleError: "Error saving vehicle",
    deleteVehicleFailed: "Failed to delete vehicle",
    deleteVehicleError: "Error deleting vehicle",
    createBookingFailed: "Failed to create booking",
    createBookingError: "Error creating booking",
    pending: "Pending",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    available: "Available",
    rented: "Rented",
    maintenance: "Maintenance",
    username: "Username",
    password: "Password",
    authenticate: "Authenticate",
    settingsSaved: "Settings saved successfully!",
    settingsSaveFailed: "Failed to save settings.",
    settingsSaveError: "Error saving settings.",
    uploadImageFailed: "Failed to upload image.",
    cmsAndSettings: "CMS & Settings",
    showDateSearchLabel: "Show Date Search on Homepage",
    saveChanges: "Save Changes",
    saving: "Saving...",
    homePageHero: "Home Page Hero",
    backgroundImage: "Background Image",
    clickUploadNewImage: "Click to Upload New Image",
    pickupLocations: "Pickup Locations",
    locationName: "Location Name",
    locationPlaceholder: "e.g. Aéroport d'Alger",
    locationType: "Type",
    airport: "Airport",
    cityCenter: "City Center",
    marinaBeach: "Marina / Beach",
    vehicleCategories: "Vehicle Categories",
    inboxMessages: "Inbox Messages",
    unread: "unread",
    noMessages: "No messages yet",
    noContactRequests: "No contact requests have been submitted yet.",
    deleteMessageConfirm: "Delete this message?",
    from: "From",
    date: "Date",
    markRead: "Mark Read",
    markUnread: "Mark Unread",
    delete: "Delete",
    failedToggleVisibility: "Failed to toggle visibility",
    deleteCategoryConfirm: "Are you sure you want to delete this category? This might affect existing vehicles.",
    failedDeleteCategory: "Failed to delete category",
    categoryNameRequired: "Category name is required",
    failedSaveCategory: "Failed to save category",
    failedCreateCategory: "Failed to create category",
    addCategory: "Add Category",
    newCategoryName: "New Category Name",
    categoryPlaceholder: "e.g. SUV, Yacht...",
    categoryName: "Category Name",
    subcategories: "Subcategories",
    noSubcategories: "No subcategories yet.",
    addSubcategoryPlaceholder: "Add new subcategory...",
    visible: "Visible",
    hidden: "Hidden",
    clientsDatabase: "Clients Database",
    exportExcel: "Export to Excel",
    totalSpent: "Total Spent",
    lastRental: "Last Rental",
    active: "Active",
    inactive: "Inactive",
    totalSpentLabel: "Total Spent (DA)",
    lastRentalDateLabel: "Last Rental Date",
    noClientsFound: "No clients found.",
    editBooking: "Edit Booking",
    editReservation: "Edit Reservation",
    updateBooking: "Update Booking",
    updating: "Updating...",
    updateBookingFailed: "Failed to update booking",
    updateBookingError: "Error updating booking",
    viewMode: "View Mode",
    tableView: "Table View",
    gridView: "Grid View",
    // Custom keys
    allVehicles: "All Vehicles",
    aboutThisVehicle: "About this Vehicle",
    rentalRequirements: "Rental Requirements",
    conditionsLabel: "Conditions",
    unavailableDatesLabel: "Unavailable Dates:",
    editionLabel: "Edition",
    toWord: "to",
    todayPreset: "Today",
    tomorrowPreset: "Tomorrow",
    weekendPreset: "This Weekend",
    nextWeekPreset: "Next Week",
    transmissionLabel: "Transmission",
    fuelLabel: "Fuel",
    ccLabel: "Engine Size (cc)",
    horsepowerLabel: "Horsepower",
    helmetIncludedLabel: "Helmet Included",
    lifeJacketsIncludedLabel: "Life Jackets Included",
    automatic: "Automatic",
    manual: "Manual",
    petrol: "Petrol",
    diesel: "Diesel",
    electric: "Electric",
    hybrid: "Hybrid",
    yes: "Yes",
    no: "No",
    summaryStep: "Summary",
    addonsStep: "Add-ons",
    detailsStep: "Details",
    confirmStep: "Confirmed",
    backToVehicle: "Back to vehicle",
    estimatedTotal: "Estimated Total",
    yourInformation: "Your Information",
    driverNameLabel: "Full Name",
    driverNamePlaceholder: "Your full name",
    fullNamePlaceholder: "Your full name",
    payOnPickupDesc: "Pay On Pickup — No charges now",
    processing: "Processing...",
    confirmBooking: "Confirm Reservation",
    rateLabel: "Rate",
    durationLabel: "Duration",
    baseRentalLabel: "Base rental",
    quickReservation: "Quick Reservation",
    selectPickupLocation: "Please select a pickup location",
    returnDateAfterPickup: "Return date & time must be after pickup date & time",
    bookingSuccess: "Booking successful! We will contact you shortly.",
    premiumSelection: "Premium Selection",
    flatRateTrip: "Flat rate for the trip",
    pricedPerUnit: "Priced per duration unit",
    pricedPerDurationUnit: "Priced per duration unit",
    free: "Free",
    noAddonsAvailable: "No extra options available for this vehicle.",
    secureBookingInfo: "Secure Booking",
    payOnPickupInfo: "Pay on pickup",
    dataSafeProtected: "Your data is safe and protected",
    allSet: "You're all set!",
    hoursCountUnit: "hours",
    hourCountUnit: "hour",
    halfDaysCountUnit: "half-days",
    halfDayCountUnit: "half-day",
    daysCountUnit: "days",
    dayCountUnit: "day",
    car: "Car",
    motorcycle: "Motorcycle",
    jetski: "Jet Ski",
    securityDepositLabel: "Security Deposit (Caution - Optional)",
    cautionOptionalTitle: "Security Deposit (Caution) - Optional",
    cautionOptionalDesc: "Fully refundable upon safe return of the vehicle",
    optional: "Optional Choice",
    payOnPickup: "Handle Caution on Site at Agency",
    standardCautionNotice: "Pay deposit directly upon pick-up",
    includeCautionInBooking: "Register Caution Deposit in Booking",
    refundable: "Refundable",
    cautionRegistered: "Caution registered",
    cautionPayableOnSite: "Caution payable on site",
    cautionRequired: "Optional security deposit choice",
    rentalRules: "Rental Rules & Conditions",
    cautionRefundableDesc: "Fully refundable upon safe return of the vehicle.",
    driverQuestion: "Need a Professional Driver?",
    driverPrompt: "Professional Driver (Chauffeur)",
    selfDrive: "Self-Drive Rental",
    withChauffeur: "Chauffeur Driven",
    driverPriceInfo: "hire a local driver to navigate traffic easily",
    driverOptionLabel: "Chauffeur Service Options",
    driverEnabled: "Driver Service Available",
    driverDisabled: "Self-Drive Only",
    editVehicleTranslations: "Manage Translations",
    requirementsFr: "Requirements (French)",
    requirementsAr: "Requirements (Arabic)",
    conditionsFr: "Conditions (French)",
    conditionsAr: "Conditions (Arabic)",
    descriptionFr: "Description (French)",
    descriptionAr: "Description (Arabic)",
    extraOptionsTitle: "Extra Options & Add-ons",
    extraOptionsSubtitle: "Manage rentable extras like GPS, Helmets, or Baby Seats.",
    addNewOption: "Add New Option",
    optionName: "Option Name",
    price: "Price",
    bindingRule: "Binding Rule",
    actions: "Actions",
    globalAll: "Global (All Vehicles)",
    categoryRule: "Specific Category",
    vehicleRule: "Specific Vehicle",
    flatRateLabel: "Flat Rate (Per Trip)",
    pricedPerDay: "Per Day / Rental Unit",
    editOption: "Edit Option",
    newExtraOption: "New Extra Option",
    optionNameEn: "Option Name (English)",
    nameFr: "Name (French)",
    nameAr: "Name (Arabic)",
    priceDa: "Price (DA)",
    priceType: "Price Type",
    adminSelectCategory: "Select Category",
    adminSelectVehicle: "Select Vehicle",
    chooseVehicle: "-- Choose a Vehicle --",
    saveOption: "Save Option",
    noExtraOptionsFound: "No extra options found",
    loadingOptions: "Loading options...",
    extraOptions: "Options & Add-ons",
    revenueTrendTitle: "Revenue & Bookings Trend",
    revenueTrendSubtitle: "Monthly overview of platform performance",
    generalSettings: "General Settings",
    heroAndBranding: "Hero & Branding",
    aboutUsTab: "About Us (Notre Histoire)",
    agencyLocationsTab: "Agency Locations",
    generalConfiguration: "General Configuration",
    storeName: "Store Name",
    globalAgencyPhone: "Global Agency Phone",
    globalAgencyEmail: "Global Agency Email",
    globalAgencyAddress: "Global Agency Address",
    storeLogo: "Store Logo",
    removeLogo: "Remove Logo",
    brandColors: "Brand Colors",
    preview: "Preview",
    primaryColor: "Primary Color",
    secondaryColor: "Secondary Color",
    showSearchWidget: "Show Search Widget",
    showSearchWidgetDesc: "Activer ou désactiver le bloc de recherche sur la page d'accueil."
  },
  fr_temp: {
    // Navbar
    home: "Accueil",
    fleet: "Flotte",
    admin: "Dashboard Admin",
    backToWeb: "Retour au Site",
    aboutUs: "À Propos",
    aboutTitle: "Notre Histoire",
    aboutSubtitleText: "LuxeRent propose une sélection incomparable de véhicules de prestige conçue pour rendre vos trajets extraordinaires.",
    aboutStoryTitle: "La Vision LuxeRent",
    aboutStoryText1: "Né d'une passion pour le luxe et l'ingénierie d'exception, LuxeRent est bien plus qu'une agence de location de véhicules. Nous créons des voyages mémorables en proposant une flotte d'élite de voitures de sport, supermotos et jet-skis.",
    aboutStoryText2: "Nos valeurs clés : pas de dépôt de réservation en ligne, la simplicité du paiement sur place, et un service d'assistance personnalisé 24h/24 et 7j/7, pour vous garantir une tranquillité d'esprit absolue.",
    ourLocations: "Nos Agences",
    monacoGarage: "Terminal Aéroport d'Alger",
    monacoGarageAddress: "Terminal 2, Aéroport International Houari Boumédiène, Alger",
    niceAirport: "Agence Centrale d'Oran",
    niceAirportAddress: "Boulevard Emir Abdelkader, Centre Ville, Oran",
    operatingHours: "Heures d'Ouverture",
    operatingHoursVal: "Lundi - Dimanche : 08:00 - 22:00",
    contactUs: "Contactez-Nous",
    fullName: "Nom Complet",
    emailAddress: "Adresse E-mail",
    subject: "Sujet",
    message: "Votre Message",
    selectSubject: "Sélectionnez un sujet",
    generalInquiry: "Demande Générale",
    partnership: "Partenariat Commercial",
    vipRequest: "Réservation Personnalisée VIP",
    submitMessage: "Envoyer le Message",
    sending: "Envoi en cours...",
    messageSent: "Message envoyé avec succès !",
    messageSentDesc: "Nous vous recontacterons dans les 2 prochaines heures.",
    ourStoryTag: "Notre Histoire",
    ourLocationsSubtitle: "Récupérez vos véhicules en toute simplicité dans nos agences de prestige.",
    completeTrustTitle: "Confiance Totale",
    completeTrustDesc: "Zéro caution, paiement sur place transparent",
    premiumQualityTitle: "Qualité Premium",
    premiumQualityDesc: "Flotte de luxe soigneusement révisée et nettoyée",
    totalFlexibilityTitle: "Flexibilité Totale",
    totalFlexibilityDesc: "Annulations gratuites et assistance 24h/24",
    flexibleHoursTitle: "Horaires Flexibles",
    flexibleHoursDesc: "Service de prise en charge tôt ou tard",
    contactUsSubtitle: "Une question, un partenariat ou une demande personnalisée ? Écrivez-nous.",
    newMessage: "Nouveau message",
    howCanWeHelp: "Comment pouvons-nous vous aider ?",
    addressLabel: "Adresse",
    phoneFieldLabel: "Téléphone",
    emailFieldLabel: "E-mail",
    mapView: "Itinéraire",
    noLocationsConfigured: "Aucune agence configurée.",

    // Homepage Hero
    heroBadge: "Disponible dès maintenant : Collection 2026",
    heroTitle1: "Le frisson de la",
    heroTitle2: "location premium",
    heroSubtitle: "Faites votre choix parmi notre flotte exclusive de voitures, motos et jet-skis. Payez facilement sur place à la récupération de votre véhicule.",
    pickupLocation: "Lieu de prise en charge",
    rentalDates: "Dates & Heures de location",
    searchFleet: "Rechercher",
    selectLocation: "Sélectionnez un emplacement",
    vehiclesStat: "Véhicules",
    satisfactionStat: "Avis clients",
    categoriesStat: "Catégories",
    supportStat: "Support 24/7",
    pickupLocationError: "Veuillez sélectionner un lieu de prise en charge",
    returnDateError: "La date et l'heure de retour doivent être après la date et l'heure de prise en charge",
    yourNameLabel: "Votre nom",
    confirmReservation: "Confirmer la réservation",

    // Vitrine sections
    browseCategories: "Catégories de Flotte",
    discoverFleet: "Découvrez notre sélection exclusive",
    featuredVehicles: "Collection Premium",
    exploreFavorites: "Découvrez les coups de cœur de nos clients",
    viewAllFleet: "Voir toute la flotte",
    quickReserve: "Réserver",
    payLater: "Payer Plus Tard",
    whyChooseUs: "Pourquoi Choisir LuxeRent ?",
    qualityService: "Qualité & Service Premium",
    qualityServiceDesc: "Tous nos véhicules subissent des contrôles de qualité rigoureux pour garantir sécurité et tranquillité d'esprit.",
    payOnSite: "Paiement Sur Place",
    payOnSiteDesc: "Zéro frais initiaux. Payez en toute sécurité lors de la récupération du véhicule dans notre agence.",
    topPerformance: "Performance Maximale",
    topPerformanceDesc: "Entretien régulier et nettoyage minutieux pour garder les moteurs vifs et les carrosseries étincelantes.",
    premiumSupport: "Support Premium 24/7",
    premiumSupportDesc: "Nous sommes toujours prêts à vous assister à tout moment de votre voyage.",
    cars: "Voitures",
    motorcycles: "Motos",
    jetskis: "Jet Skis",

    // Fleet page
    ourFleet: "Notre Flotte Premium",
    fleetSubtitle: "Sélectionnez le véhicule idéal pour votre prochaine aventure.",
    filters: "Filtres",
    maxPrice: "Prix Max",
    transmission: "Transmission",
    fuelType: "Carburant",
    clearFilters: "Effacer les filtres",
    showingAll: "Affichage de tous les résultats",
    activeFilters: "Filtres Actifs :",
    clearAll: "Tout effacer",
    noVehiclesMatch: "Aucun véhicule ne correspond",
    resetFiltersDesc: "Essayez de modifier vos filtres pour trouver le véhicule idéal.",
    resetAllFilters: "Réinitialiser les filtres",
    reserveNow: "Réserver",

    // Detail page
    specifications: "Spécifications",
    whyRentWithUs: "Pourquoi réserver chez nous ?",
    excellentCondition: "Excellent État",
    excellentConditionDesc: "Tous nos véhicules sont régulièrement entretenus et vérifiés avant chaque location pour votre sécurité.",
    payOnSiteTitle: "Paiement Sur Place",
    payOnSiteDetail: "Pas de carte de crédit requise en ligne. Payez en toute sécurité lors de la prise en charge dans notre agence.",
    reservePayLater: "Réserver maintenant (Paiement sur place)",
    secureBooking: "Réservation sécurisée. Zéro coût initial.",

    // Checkout page
    bookingSummary: "Résumé de Réservation",
    continueAddons: "Continuer vers les options",
    enhanceTrip: "Optimisez votre voyage",
    enhanceYourTrip: "Personnalisez votre voyage",
    freeCancellation: "Annulation Gratuite",
    freeCancellationDesc: "Annulez gratuitement à tout moment. Aucun paiement en ligne requis aujourd'hui.",
    continueDetails: "Continuer vers vos détails",
    driverInfo: "Informations Conducteur",
    phoneNumber: "Numéro de téléphone",
    docVerification: "Vérification des Documents",
    verificationDetail: "Veuillez noter que vous devrez présenter votre permis de conduire et une pièce d'identité valides lors de la prise en charge.",
    clickUpload: "Cliquez pour charger les documents (Optionnel)",
    completeReservation: "Finaliser la réservation",
    reservationConfirmed: "Réservation Confirmée !",
    bookingSecured: "Votre réservation a été validée avec succès. Veuillez apporter votre permis de conduire et votre moyen de paiement au lieu de prise en charge.",
    backToHome: "Retour à l'Accueil",
    priceDetails: "Détails du Prix",
    rentalPrice: "Prix de Location",
    baseCost: "Coût de Base",
    addOns: "Options additionnelles",
    totalPrice: "Prix Total",
    payablePickup: "À régler sur place",
    luxeGuarantee: "Garantie LuxeRent",
    luxeGuaranteeDesc: "Pas d'acompte requis. Annulez gratuitement à tout moment avant la prise en charge du véhicule.",
    summary: "Résumé",
    details: "Détails",
    confirm: "Confirmation",

    // Admin page
    adminPortal: "Portail Administrateur",
    enterPasscode: "Veuillez saisir le code d'accès pour accéder au tableau de bord.",
    verifyPasscode: "Valider l'Accès",
    passcodePlaceholder: "Code secret admin",
    wrongPasscode: "Code incorrect. Veuillez réessayer.",
    bookingLogs: "Réservations Clients",
    fleetManager: "Gestion de Flotte",
    addVehicle: "Ajouter un véhicule",
    editVehicle: "Modifier le véhicule",
    totalBookings: "Total Réservations",
    activeClients: "Clients Actifs",
    pendingApprovals: "En attente d'approbation",
    recentReservations: "Réservations Récentes",
    make: "Marque",
    model: "Modèle",
    year: "Année",
    pricePerDay: "Prix par Jour (DA)",
    pricePerHour: "Prix par Heure (DA)",
    category: "Catégorie",
    imageUrl: "URL de l'image",
    doors: "Portes",
    cc: "Cylindrée (cc)",
    horsepower: "Chevaux (ch)",
    features: "Caractéristiques",
    save: "Enregistrer les modifications",
    cancel: "Annuler",
    deleteConfirm: "Êtes-vous sûr de vouloir supprimer ce véhicule ?",
    dashboard: "Tableau de Bord",
    categories: "Catégories",
    messages: "Messages",
    settings: "Paramètres",
    refresh: "Rafraîchir",
    seedData: "Données de Test",
    seeding: "Génération...",
    logout: "Déconnexion",
    newBooking: "Nouvelle Réservation",
    newReservation: "Nouvelle Réservation",
    guestInformation: "Informations Client",
    fullNameLabel: "Nom Complet *",
    phoneLabel: "Téléphone *",
    emailLabel: "E-mail *",
    vehicleAndSchedule: "Véhicule & Calendrier",
    vehicleLabel: "Véhicule *",
    pickupDateTime: "Date & Heure de Départ *",
    returnDateTime: "Date & Heure de Retour *",
    pickupLocationLabel: "Lieu de Départ *",
    rentalDurationType: "Type de durée *",
    createBooking: "Créer la Réservation",
    creating: "Création...",
    pricingTiersAndDiscounts: "Tarifs & Réductions",
    pricePerHourLabel: "Prix par Heure (DA)",
    pricePerHalfDayLabel: "Prix par Demi-Journée (12h) (DA)",
    pricePerDayLabel: "Prix par Jour (24h) (DA)",
    discountPercentageLabel: "Pourcentage de Réduction (%)",
    discountLabel: "Nom de la Promo",
    description: "Description",
    requirements: "Conditions Requises",
    conditions: "Conditions d'Utilisation",
    hourly: "À l'heure",
    halfDay: "Demi-journée (12h)",
    daily: "Par jour (24h)",
    revenueBookingsTrend: "Tendance des Revenus & Réservations",
    monthlyOverview: "Aperçu mensuel des performances de la plateforme",
    stableGrowth: "Croissance Stable",
    adminSubtitle: "Gérez votre flotte premium et les réservations de vos clients.",
    guestDetails: "Détails du Client",
    vehicle: "Véhicule",
    schedule: "Calendrier",
    location: "Lieu",
    total: "Total",
    status: "Statut",
    loadingReservations: "Chargement des réservations...",
    noBookingsFound: "Aucune réservation trouvée.",
    loadingFleet: "Chargement de la flotte...",
    emptyFleet: "Flotte Vide",
    noVehiclesAdded: "Aucun véhicule n'a encore été ajouté.",
    standard: "Standard",
    doorsLabel: "Portes",
    perDay: "jour",
    perHr: "heure",
    subcategoryLabel: "Sous-catégorie",
    none: "Aucun",
    disableHint: "(0 pour désactiver)",
    noDiscountHint: "(0 pour aucune réduction)",
    descriptionPlaceholder: "Description du véhicule",
    requirementsPlaceholder: "Ex : Permis de conduire valide, 21 ans et plus",
    conditionsPlaceholder: "Ex : Non fumeur, Retour avec le plein",
    landingImageLabel: "Image de présentation (Section Description)",
    clickDragUpload: "Cliquez ou glissez pour charger l'image de présentation",
    blockedDates: "Dates Bloquées",
    startDate: "Date de Début",
    endDate: "Date de Fin",
    add: "Ajouter",
    vehiclePhoto: "Photo du véhicule",
    imageUploaded: "Image chargée",
    changeImage: "Changer d'image",
    uploadVehiclePhoto: "Télécharger une photo de véhicule",
    recommendedFormats: "Format recommandé : PNG, JPG, JPEG ou WEBP",
    selectVehicle: "Sélectionner un véhicule",
    rentalDurationTypeLabel: "Type de durée *",
    hour: "Heure",
    halfDayLabel: "Demi-journée (12h)",
    dayLabel: "Jour (24h)",
    pickupLocationPlaceholder: "Ex : Aéroport d'Alger",
    uploadFailed: "Échec du téléchargement",
    invalidUploadResponse: "Réponse invalide du serveur",
    uploadError: "Erreur lors du téléchargement",
    loginFailed: "Échec de la connexion",
    networkError: "Erreur réseau. Veuillez vérifier votre connexion.",
    seedSuccess: "Base de test générée avec succès !",
    seedNonJson: "Base générée, mais réponse non-JSON du serveur.",
    seedFailed: "Échec de la génération de la base de test.",
    statusUpdateFailed: "Échec de la mise à jour du statut",
    statusUpdateError: "Erreur lors de la mise à jour du statut",
    saveVehicleFailed: "Échec de l'enregistrement du véhicule",
    saveVehicleError: "Erreur lors de l'enregistrement du véhicule",
    deleteVehicleFailed: "Échec de la suppression du véhicule",
    deleteVehicleError: "Erreur lors de la suppression du véhicule",
    createBookingFailed: "Échec de la création de la réservation",
    createBookingError: "Erreur lors de la création de la réservation",
    pending: "En attente",
    confirmed: "Confirmé",
    completed: "Terminé",
    cancelled: "Annulé",
    available: "Disponible",
    rented: "Loué",
    maintenance: "Maintenance",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    authenticate: "S'authentifier",
    settingsSaved: "Paramètres sauvegardés avec succès !",
    settingsSaveFailed: "Échec de la sauvegarde des paramètres.",
    settingsSaveError: "Erreur lors de la sauvegarde des paramètres.",
    uploadImageFailed: "Échec du chargement de l'image.",
    cmsAndSettings: "CMS & Paramètres",
    showDateSearchLabel: "Afficher la recherche par date sur la page d'accueil",
    saveChanges: "Enregistrer les modifications",
    saving: "Enregistrement...",
    homePageHero: "Bannière Page d'Accueil",
    backgroundImage: "Image d'arrière-plan",
    clickUploadNewImage: "Cliquez pour charger une nouvelle image",
    pickupLocations: "Lieux de prise en charge",
    locationName: "Nom du lieu",
    locationPlaceholder: "Ex : Aéroport d'Alger",
    locationType: "Type",
    airport: "Aéroport",
    cityCenter: "Centre-ville",
    marinaBeach: "Port / Plage",
    vehicleCategories: "Catégories de véhicules",
    inboxMessages: "Boîte de réception",
    unread: "non lu(s)",
    noMessages: "Aucun message",
    noContactRequests: "Il n'y a pas encore de demandes de contact.",
    deleteMessageConfirm: "Supprimer ce message ?",
    from: "De",
    date: "Date",
    markRead: "Marquer Lu",
    markUnread: "Marquer Non Lu",
    delete: "Supprimer",
    failedToggleVisibility: "Échec du basculement de la visibilité",
    deleteCategoryConfirm: "Êtes-vous sûr de vouloir supprimer cette catégorie ? Cela peut affecter les véhicules existants.",
    failedDeleteCategory: "Échec de la suppression de la catégorie",
    categoryNameRequired: "Le nom de la catégorie est requis",
    failedSaveCategory: "Échec de l'enregistrement de la catégorie",
    failedCreateCategory: "Échec de la création de la catégorie",
    addCategory: "Ajouter une catégorie",
    newCategoryName: "Nom de la nouvelle catégorie",
    categoryPlaceholder: "Ex : SUV, Yacht...",
    categoryName: "Nom de la catégorie",
    subcategories: "Sous-catégories",
    noSubcategories: "Aucune sous-catégorie pour le moment.",
    addSubcategoryPlaceholder: "Ajouter une sous-catégorie...",
    visible: "Visible",
    hidden: "Masqué",
    clientsDatabase: "Base de données clients",
    exportExcel: "Exporter vers Excel",
    totalSpent: "Total dépensé",
    lastRental: "Dernière location",
    active: "Actif",
    inactive: "Inactif",
    totalSpentLabel: "Total dépensé (DA)",
    lastRentalDateLabel: "Date de dernière location",
    noClientsFound: "Aucun client trouvé.",
    editBooking: "Modifier la réservation",
    editReservation: "Modifier la réservation",
    updateBooking: "Mettre à jour",
    updating: "Mise à jour...",
    updateBookingFailed: "Échec de la mise à jour de la réservation",
    updateBookingError: "Erreur lors de la mise à jour de la réservation",
    viewMode: "Mode d'affichage",
    tableView: "Tableau",
    gridView: "Grille",
    // Custom keys
    allVehicles: "Toute la Flotte",
    aboutThisVehicle: "À propos de ce véhicule",
    rentalRequirements: "Conditions de Location",
    conditionsLabel: "Conditions d'Utilisation",
    unavailableDatesLabel: "Dates d'Indisponibilité :",
    editionLabel: "Édition",
    toWord: "à",
    todayPreset: "Aujourd'hui",
    tomorrowPreset: "Demain",
    weekendPreset: "Ce Week-end",
    nextWeekPreset: "Sem. Prochaine",
    transmissionLabel: "Transmission",
    fuelLabel: "Carburant",
    ccLabel: "Cylindrée (cc)",
    horsepowerLabel: "Puissance (ch)",
    helmetIncludedLabel: "Casque Inclus",
    lifeJacketsIncludedLabel: "Gilets de Sauvetage",
    automatic: "Automatique",
    manual: "Manuelle",
    petrol: "Essence",
    diesel: "Diesel",
    electric: "Électrique",
    hybrid: "Hybride",
    yes: "Oui",
    no: "Non",
    summaryStep: "Résumé",
    addonsStep: "Options",
    detailsStep: "Détails",
    confirmStep: "Confirmé",
    backToVehicle: "Retour au véhicule",
    estimatedTotal: "Total estimé",
    yourInformation: "Vos informations",
    driverNameLabel: "Nom complet",
    driverNamePlaceholder: "Votre nom complet",
    fullNamePlaceholder: "Votre nom complet",
    payOnPickupDesc: "Paiement sur place — Aucun frais maintenant",
    processing: "Traitement...",
    confirmBooking: "Confirmer ma réservation",
    rateLabel: "Tarif",
    durationLabel: "Durée",
    baseRentalLabel: "Location de base",
    quickReservation: "Réservation Rapide",
    selectPickupLocation: "Veuillez sélectionner un lieu de prise en charge",
    returnDateAfterPickup: "La date de retour doit être après la date de départ",
    bookingSuccess: "Réservation réussie ! Nous vous contacterons sous peu.",
    premiumSelection: "Sélection Premium",
    flatRateTrip: "Frais fixes pour tout le séjour",
    pricedPerUnit: "Prix par unité de temps",
    pricedPerDurationUnit: "Prix par unité de temps",
    free: "Gratuit",
    noAddonsAvailable: "Aucune option supplémentaire disponible pour ce véhicule.",
    secureBookingInfo: "Réservation sécurisée",
    payOnPickupInfo: "Paiement sur place",
    dataSafeProtected: "Données sécurisées et protégées",
    allSet: "C'est tout bon !",
    hoursCountUnit: "heures",
    hourCountUnit: "heure",
    halfDaysCountUnit: "demi-journées",
    halfDayCountUnit: "demi-journée",
    daysCountUnit: "jours",
    dayCountUnit: "jour",
    car: "Voiture",
    motorcycle: "Moto",
    jetski: "Jet Ski",
    securityDepositLabel: "Caution (Dépôt de Garantie - Optionnelle)",
    cautionOptionalTitle: "Dépôt de Garantie (Caution) - Optionnel",
    cautionOptionalDesc: "Entièrement remboursable au retour du véhicule en bon état",
    optional: "Choix Optionnel",
    payOnPickup: "Gérer la caution sur place à l'agence",
    standardCautionNotice: "Régler le dépôt directement lors de la récupération",
    includeCautionInBooking: "Enregistrer la caution dans la réservation",
    refundable: "Remboursable",
    cautionRegistered: "Caution enregistrée",
    cautionPayableOnSite: "Caution payable sur place",
    cautionRequired: "Dépôt de caution facultatif selon formule",
    rentalRules: "Règlement & Conditions de location",
    cautionRefundableDesc: "Entièrement remboursable au retour du véhicule en bon état.",
    driverQuestion: "Besoin d'un chauffeur professionnel ?",
    driverPrompt: "Chauffeur professionnel",
    selfDrive: "Sans Chauffeur (Conduite libre)",
    withChauffeur: "Avec Chauffeur",
    driverPriceInfo: "louez un chauffeur local pour naviguer facilement dans le trafic",
    driverOptionLabel: "Service Chauffeur",
    driverEnabled: "Service Chauffeur Disponible",
    driverDisabled: "Conduite Libre Uniquement",
    editVehicleTranslations: "Gérer les Traductions",
    requirementsFr: "Conditions (Français)",
    requirementsAr: "Conditions (Arabe)",
    conditionsFr: "Conditions (Français)",
    conditionsAr: "Conditions (Arabe)",
    descriptionFr: "Description (Français)",
    descriptionAr: "Description (Arabe)",
    extraOptionsTitle: "Options & Équipements Supplémentaires",
    extraOptionsSubtitle: "Gérez les équipements louables comme le GPS, les casques ou sièges bébé.",
    addNewOption: "Ajouter une option",
    optionName: "Nom de l'option",
    price: "Prix",
    bindingRule: "Règle d'attribution",
    actions: "Actions",
    globalAll: "Global (Tous véhicules)",
    categoryRule: "Catégorie spécifique",
    vehicleRule: "Véhicule spécifique",
    flatRateLabel: "Tarif Fixe (Par séjour)",
    pricedPerDay: "Par Jour / Unité",
    editOption: "Modifier l'option",
    newExtraOption: "Nouvelle option supplémentaire",
    optionNameEn: "Nom de l'option (Anglais)",
    nameFr: "Nom (Français)",
    nameAr: "Nom (Arabe)",
    priceDa: "Prix (DA)",
    priceType: "Type de tarification",
    adminSelectCategory: "Sélectionnez la catégorie",
    adminSelectVehicle: "Sélectionnez le véhicule",
    chooseVehicle: "-- Choisir un véhicule --",
    saveOption: "Enregistrer l'option",
    noExtraOptionsFound: "Aucune option supplémentaire trouvée",
    loadingOptions: "Chargement des options...",
    extraOptions: "Options & Équipements",
    revenueTrendTitle: "Tendance des Revenus & Réservations",
    revenueTrendSubtitle: "Aperçu mensuel des performances de la plateforme",
    generalSettings: "Paramètres Généraux",
    heroAndBranding: "Héros & Image de marque",
    aboutUsTab: "À Propos (Notre Histoire)",
    agencyLocationsTab: "Agences",
    generalConfiguration: "Configuration Générale",
    storeName: "Nom de l'Agence",
    globalAgencyPhone: "Téléphone Principal",
    globalAgencyEmail: "Email Principal",
    globalAgencyAddress: "Adresse Principale",
    storeLogo: "Logo de l'Agence",
    removeLogo: "Supprimer le logo",
    brandColors: "Couleurs de la marque",
    preview: "Aperçu",
    primaryColor: "Couleur Principale",
    secondaryColor: "Couleur Secondaire",
    showSearchWidget: "Afficher le bloc de recherche",
    showSearchWidgetDesc: "Activer ou désactiver complètement le bloc de recherche sur la page d'accueil."
  }
};

/* const _unusedAr = {
    // Navbar
    home: "الرئيسية",
    fleet: "أسطولنا",
    admin: "لوحة التحكم",
    backToWeb: "العودة للموقع",
    aboutUs: "من نحن",
    aboutTitle: "قصتنا",
    aboutSubtitleText: "تقدم LuxeRent تشكيلة لا مثيل لها من المركبات الفاخرة والشعبية المصممة لتجعل رحلتكم استثنائية في الجزائر.",
    aboutStoryTitle: "رؤية LuxeRent",
    aboutStoryText1: "تأسست LuxeRent بشغف كبير بالفخامة وجودة الخدمة، وهي أكثر من مجرد وكالة لتأجير السيارات. نحن نصنع تجارب سفر لا تُنسى في الجزائر من خلال تقديم أسطول نخبة من السيارات الفاخرة والشعبية.",
    aboutStoryText2: "قيمنا الأساسية واضحة وموثوقة: بدون دفعات أولية، الدفع عند الاستلام بكل مرونة، وخدمة عملاء استثنائية 24/7 لضمان راحتكم الكاملة.",
    ourLocations: "مواقع الاستلام الخاصة بنا",
    monacoGarage: "مطار هواري بومدين الدولي (الجزائر العاصمة)",
    monacoGarageAddress: "محطة المغادرة 2، مطار هواري بومدين، الجزائر العاصمة",
    niceAirport: "وكالة وهران وسط المدينة",
    niceAirportAddress: "شارع الأمير عبد القادر، وسط المدينة، وهران",
    operatingHours: "أوقات العمل",
    operatingHoursVal: "الإثنين - الأحد: 08:00 صباحاً - 10:00 مساءً",
    contactUs: "اتصل بنا",
    fullName: "الاسم الكامل",
    emailAddress: "البريد الإلكتروني",
    subject: "الموضوع",
    message: "الرسالة",
    selectSubject: "اختر موضوع الرسالة",
    generalInquiry: "استفسار عام",
    partnership: "شراكة تجارية",
    vipRequest: "طلب VIP خاص",
    submitMessage: "إرسال الرسالة",
    sending: "جاري الإرسال...",
    messageSent: "تم إرسال الرسالة بنجاح!",
    messageSentDesc: "سنتصل بك في غضون الساعتين القادمتين.",
    ourStoryTag: "قصتنا",
    ourLocationsSubtitle: "استلم مركباتك الفاخرة بكل سهولة من وكالاتنا المتميزة.",
    completeTrustTitle: "ثقة كاملة",
    completeTrustDesc: "بدون دفعات أولية، دفع شفاف عند الاستلام",
    premiumQualityTitle: "جودة عالية",
    premiumQualityDesc: "أسطول فاخر مفحوص ومصان بعناية فائقة",
    totalFlexibilityTitle: "مرونة كاملة",
    totalFlexibilityDesc: "إلغاء مجاني ودعم على مدار الساعة",
    flexibleHoursTitle: "ساعات عمل مرنة",
    flexibleHoursDesc: "خدمة استلام متوفرة في الصباح الباكر أو المواعيد المتأخرة",
    contactUsSubtitle: "هل لديك سؤال، شراكة، أو طلب VIP خاص؟ اكتب إلينا.",
    newMessage: "رسالة جديدة",
    howCanWeHelp: "كيف يمكننا مساعدتك؟",
    addressLabel: "العنوان",
    phoneFieldLabel: "الهاتف",
    emailFieldLabel: "البريد الإلكتروني",
    mapView: "عرض الخريطة",
    noLocationsConfigured: "لم يتم تكوين أي وكالات.",

    // Homepage Hero
    heroBadge: "متوفر الآن: تشكيلة 2024",
    heroTitle1: "متعة القيادة و",
    heroTitle2: "التأجير الفاخر في الجزائر",
    heroSubtitle: "اختر من بين أسطولنا الحصري من السيارات الفاخرة والشعبية، الدراجات النارية، والجيت سكي. ادفع بسهولة في موقع الوكالة عند استلام مركبتك.",
    pickupLocation: "مكان الاستلام",
    rentalDates: "تاريخ ووقت الإيجار",
    searchFleet: "البحث في الأسطول",
    selectLocation: "اختر موقع الاستلام",
    vehiclesStat: "مركبات",
    satisfactionStat: "تقييم العملاء",
    categoriesStat: "فئات",
    supportStat: "دعم متواصل",
    pickupLocationError: "يرجى اختيار موقع الاستلام",
    returnDateError: "تاريخ ووقت العودة يجب أن يكون بعد تاريخ ووقت الاستلام",
    yourNameLabel: "الاسم",
    confirmReservation: "تأكيد الحجز",

    // Vitrine sections
    browseCategories: "تصفح الفئات",
    discoverFleet: "اكتشف تشكيلتنا الحصرية",
    featuredVehicles: "مجموعتنا الفاخرة",
    exploreFavorites: "اكتشف السيارات المفضلة لعملائنا",
    viewAllFleet: "عرض جميع السيارات",
    quickReserve: "حجز سريع",
    payLater: "الدفع لاحقاً",
    whyChooseUs: "لماذا تختار LuxeRent؟",
    qualityService: "جودة وخدمة ممتازة",
    qualityServiceDesc: "تخضع جميع مركباتنا لفحوصات جودة صارمة لضمان سلامتكم وراحتكم.",
    payOnSite: "الدفع عند الاستلام",
    payOnSiteDesc: "بدون أي دفعة أولى. ادفع بأمان عند استلام مركبتك في وكالتنا.",
    topPerformance: "أداء ممتاز",
    topPerformanceDesc: "صيانة دورية وتنظيف شامل للحفاظ على قوة المحرك ولمعان الهيكل.",
    premiumSupport: "دعم متميز 24/7",
    premiumSupportDesc: "جاهزون دائماً لمساعدتكم خلال فترة إيجاركم في أي وقت.",
    cars: "السيارات",
    motorcycles: "الدراجات النارية",
    jetskis: "جيت سكي",

    // Fleet page
    ourFleet: "أسطولنا المميز",
    fleetSubtitle: "اختر المركبة المثالية لمغامرتك القادمة في الجزائر.",
    filters: "الفلاتر",
    maxPrice: "السعر الأقصى",
    transmission: "ناقل الحركة",
    fuelType: "نوع الوقود",
    clearFilters: "إلغاء التصفية",
    showingAll: "عرض جميع النتائج",
    activeFilters: "الفلاتر النشطة:",
    clearAll: "مسح الكل",
    noVehiclesMatch: "لا توجد مركبات تطابق اختياراتك",
    resetFiltersDesc: "حاول تعديل خيارات التصفية للعثور على المركبة المثالية.",
    resetAllFilters: "إعادة ضبط التصفية",
    reserveNow: "حجز الآن",

    // Detail page
    specifications: "المواصفات",
    whyRentWithUs: "لماذا تستأجر منا؟",
    excellentCondition: "حالة ممتازة",
    excellentConditionDesc: "مركباتنا تخضع لصيانة دورية شاملة قبل كل عملية تأجير لضمان سلامتكم.",
    payOnSiteTitle: "الدفع عند الاستلام",
    payOnSiteDetail: "لا نطلب بطاقة ائتمانية عبر الإنترنت. ادفع بأمان عند استلام مركبتك في وكالتنا.",
    reservePayLater: "احجز الآن (الدفع عند الاستلام)",
    secureBooking: "حجز آمن 100٪. بدون دفعة أولى.",

    // Checkout page
    bookingSummary: "ملخص الحجز",
    continueAddons: "المتابعة إلى الإضافات",
    enhanceTrip: "أضف مزيداً من الراحة لرحلتك",
    enhanceYourTrip: "أضف مزيداً من الراحة لرحلتك",
    freeCancellation: "إلغاء مجاني",
    freeCancellationDesc: "إلغاء مجاني في أي وقت. لا يلزم أي دفع عبر الإنترنت اليوم.",
    continueDetails: "المتابعة لإدخال المعلومات",
    driverInfo: "معلومات السائق",
    phoneNumber: "رقم الهاتف",
    docVerification: "التحقق من الوثائق",
    verificationDetail: "يرجى ملاحظة أنه سيتعين عليك تقديم رخصة قيادة وبطاقة هوية سارية المفعول عند استلام المركبة.",
    clickUpload: "اضغط لتحميل الوثائق (اختياري)",
    completeReservation: "إإتمام الحجز",
    reservationConfirmed: "تم تأكيد الحجز بنجاح!",
    bookingSecured: "تم تأكيد حجزك بنجاح. يرجى إحضار رخصة القيادة وإثبات الدفع إلى موقع الاستلام.",
    backToHome: "العودة للرئيسية",
    priceDetails: "تفاصيل السعر",
    rentalPrice: "سعر الإيجار",
    baseCost: "التكلفة الأساسية",
    addOns: "الإضافات",
    totalPrice: "السعر الإجمالي",
    payablePickup: "المبلغ المستحق عند الاستلام",
    luxeGuarantee: "ضمان LuxeRent",
    luxeGuaranteeDesc: "بدون أي دفعة أولى. إلغاء مجاني في أي وقت قبل موعد الاستلام.",
    summary: "الملخص",
    details: "التفاصيل",
    confirm: "تأكيد الحجز",

    // Admin page
    adminPortal: "لوحة تحكم المسؤول",
    enterPasscode: "يرجى إدخال رمز الأمان للوصول إلى لوحة التحكم.",
    verifyPasscode: "التحقق من الرمز",
    passcodePlaceholder: "رمز الأمان",
    wrongPasscode: "الرمز غير صحيح. يرجى المحاولة مرة أخرى.",
    bookingLogs: "سجل الحجوزات",
    fleetManager: "إدارة الأسطول",
    addVehicle: "إضافة مركبة",
    editVehicle: "تعديل المركبة",
    totalBookings: "إجمالي الحجوزات",
    activeClients: "العملاء النشطون",
    pendingApprovals: "في انتظار الموافقة",
    recentReservations: "الحجوزات الأخيرة",
    make: "الشركة المصنعة",
    model: "الموديل",
    year: "السنة",
    pricePerDay: "السعر اليومي (د.ج)",
    pricePerHour: "السعر بالساعة (د.ج)",
    category: "الفئة",
    imageUrl: "رابط الصورة",
    doors: "الأبواب",
    cc: "حجم المحرك (cc)",
    horsepower: "القوة الحصانية",
    features: "المواصفات",
    save: "حفظ التفاصيل",
    cancel: "إلغاء",
    deleteConfirm: "هل أنت متأكد من رغبتك في حذف هذه المركبة؟",
    dashboard: "لوحة القيادة",
    categories: "الفئات",
    messages: "الرسائل",
    settings: "الإعدادات",
    refresh: "تحديث",
    seedData: "بيانات تجريبية",
    seeding: "جاري التوليد...",
    logout: "تسجيل الخروج",
    newBooking: "حجز جديد",
    newReservation: "حجز جديد",
    guestInformation: "معلومات العميل",
    fullNameLabel: "الاسم الكامل *",
    phoneLabel: "رقم الهاتف *",
    emailLabel: "البريد الإلكتروني *",
    vehicleAndSchedule: "المركبة والجدول",
    vehicleLabel: "المركبة *",
    pickupDateTime: "تاريخ ووقت الاستلام *",
    returnDateTime: "تاريخ ووقت الإرجاع *",
    pickupLocationLabel: "مكان الاستلام *",
    rentalDurationType: "نوع مدة الإيجار *",
    createBooking: "إنشاء الحجز",
    creating: "جاري الإنشاء...",
    pricingTiersAndDiscounts: "فئات الأسعار والتخفيضات",
    pricePerHourLabel: "السعر بالساعة (د.ج)",
    pricePerHalfDayLabel: "السعر لنصف يوم (12 ساعة) (د.ج)",
    pricePerDayLabel: "السعر باليوم (24 ساعة) (د.ج)",
    discountPercentageLabel: "نسبة التخفيض (%)",
    discountLabel: "مسمى التخفيض",
    description: "الوصف",
    requirements: "الشروط المطلوبة",
    conditions: "شروط الاستخدام",
    hourly: "بالساعة",
    halfDay: "نصف يوم (12 ساعة)",
    daily: "يومي (24 ساعة)",
    revenueBookingsTrend: "اتجاه الإيرادات والحجوزات",
    monthlyOverview: "نظرة عامة شهرية على أداء المنصة",
    stableGrowth: "نمو مستقر",
    adminSubtitle: "إدارة أسطولك المتميز وحجوزات العملاء الواردة.",
    guestDetails: "تفاصيل العميل",
    vehicle: "المركبة",
    schedule: "الجدول",
    location: "الموقع",
    total: "الإجمالي",
    status: "الحالة",
    loadingReservations: "جاري تحميل الحجوزات...",
    noBookingsFound: "لم يتم العثور على حجوزات.",
    loadingFleet: "جاري تحميل الأسطول...",
    emptyFleet: "الأسطول فارغ",
    noVehiclesAdded: "لم يتم إضافة أي مركبة بعد.",
    standard: "عادي",
    doorsLabel: "أبواب",
    perDay: "يوم",
    perHr: "ساعة",
    subcategoryLabel: "الفئة الفرعية",
    none: "لا يوجد",
    disableHint: "(0 للتعطيل)",
    noDiscountHint: "(0 لعدم وجود تخفيض)",
    descriptionPlaceholder: "وصف المركبة",
    requirementsPlaceholder: "مثال: رخصة قيادة سارية، 21 سنة فما فوق",
    conditionsPlaceholder: "مثال: ممنوع التدخين، إرجاع الخزان ممتلئ",
    landingImageLabel: "الصورة التعريفية (لقسم الوصف)",
    clickDragUpload: "انقر أو اسحب لتحميل الصورة التعريفية",
    blockedDates: "التواريخ المحظورة",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    add: "إضافة",
    vehiclePhoto: "صورة المركبة",
    imageUploaded: "تم تحميل الصورة",
    changeImage: "تغيير الصورة",
    uploadVehiclePhoto: "تحميل صورة المركبة",
    recommendedFormats: "الصيغ الموصى بها: PNG، JPG، JPEG أو WEBP",
    selectVehicle: "اختر مركبة",
    rentalDurationTypeLabel: "نوع مدة الإيجار *",
    hour: "ساعة",
    halfDayLabel: "نصف يوم (12 ساعة)",
    dayLabel: "يوم (24 ساعة)",
    pickupLocationPlaceholder: "مثال: مطار الجزائر",
    uploadFailed: "فشل التحميل",
    invalidUploadResponse: "استجابة غير صالحة من خادم التحميل",
    uploadError: "خطأ أثناء تحميل الملف",
    loginFailed: "فشل تسجيل الدخول",
    networkError: "خطأ في الشبكة. يرجى التحقق من اتصالك.",
    seedSuccess: "تم توليد البيانات التجريبية بنجاح!",
    seedNonJson: "تم ملء قاعدة البيانات، ولكن تم تلقي استجابة غير JSON من الخادم.",
    seedFailed: "فشل في توليد البيانات التجريبية.",
    statusUpdateFailed: "فشل تحديث الحالة",
    statusUpdateError: "خطأ أثناء تحديث الحالة",
    saveVehicleFailed: "فشل حفظ المركبة",
    saveVehicleError: "خطأ أثناء حفظ المركبة",
    deleteVehicleFailed: "فشل حذف المركبة",
    deleteVehicleError: "خطأ أثناء حذف المركبة",
    createBookingFailed: "فشل إنشاء الحجز",
    createBookingError: "خطأ أثناء إنشاء الحجز",
    pending: "قيد الانتظار",
    confirmed: "مؤكد",
    completed: "مكتمل",
    cancelled: "ملغي",
    available: "متوفر",
    rented: "مؤجر",
    maintenance: "صيانة",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    authenticate: "تسجيل الدخول",
    settingsSaved: "تم حفظ الإعدادات بنجاح!",
    settingsSaveFailed: "فشل حفظ الإعدادات.",
    settingsSaveError: "خطأ أثناء حفظ الإعدادات.",
    uploadImageFailed: "فشل تحميل الصورة.",
    cmsAndSettings: "إعدادات نظام إدارة المحتوى",
    showDateSearchLabel: "عرض البحث بالتاريخ في الصفحة الرئيسية",
    saveChanges: "حفظ التغييرات",
    saving: "جاري الحفظ...",
    homePageHero: "القسم الرئيسي للصفحة الرئيسية",
    backgroundImage: "صورة الخلفية",
    clickUploadNewImage: "انقر لتحميل صورة جديدة",
    pickupLocations: "مواقع الاستلام",
    locationName: "اسم الموقع",
    locationPlaceholder: "مثال: مطار الجزائر",
    locationType: "النوع",
    airport: "مطار",
    cityCenter: "وسط المدينة",
    marinaBeach: "ميناء / شاطئ",
    vehicleCategories: "فئات المركبات",
    inboxMessages: "صندوق الرسائل",
    unread: "غير مقروءة",
    noMessages: "لا توجد رسائل بعد",
    noContactRequests: "لم يتم إرسال أي طلبات اتصال بعد.",
    deleteMessageConfirm: "هل أنت متأكد من حذف هذه الرسالة؟",
    from: "من",
    date: "التاريخ",
    markRead: "تحديد كمقروء",
    markUnread: "تحديد كغير مقروء",
    delete: "حذف",
    failedToggleVisibility: "فشل تبديل الرؤية",
    deleteCategoryConfirm: "هل أنت متأكد من حذف هذه الفئة؟ قد يؤثر هذا على المركبات الحالية.",
    failedDeleteCategory: "فشل حذف الفئة",
    categoryNameRequired: "اسم الفئة مطلوب",
    failedSaveCategory: "فشل حفظ الفئة",
    failedCreateCategory: "فشل إنشاء الفئة",
    addCategory: "إضافة فئة",
    newCategoryName: "اسم الفئة الجديدة",
    categoryPlaceholder: "مثال: سيارة دفع رباعي، يخت...",
    categoryName: "اسم الفئة",
    subcategories: "الفئات الفرعية",
    noSubcategories: "لا توجد فئات فرعية بعد.",
    addSubcategoryPlaceholder: "إضافة فئة فرعية جديدة...",
    visible: "مرئي",
    hidden: "مخفي",
    clientsDatabase: "قاعدة بيانات العملاء",
    exportExcel: "تصدير إلى إكسل",
    totalSpent: "إجمالي الإنفاق",
    lastRental: "آخر إيجار",
    active: "نشط",
    inactive: "غير نشط",
    totalSpentLabel: "إجمالي الإنفاق (د.ج)",
    lastRentalDateLabel: "تاريخ آخر إيجار",
    noClientsFound: "لم يتم العثور على عملاء.",
    editBooking: "تعديل الحجز",
    editReservation: "تعديل الحجز",
    updateBooking: "تحديث الحجز",
    updating: "جاري التحديث...",
    updateBookingFailed: "فشل تحديث الحجز",
    updateBookingError: "خطأ أثناء تحديث الحجز",
    viewMode: "طريقة العرض",
    tableView: "عرض جدول",
    gridView: "عرض شبكة",
    // Custom keys
    allVehicles: "كل الأسطول",
    aboutThisVehicle: "حول هذه المركبة",
    rentalRequirements: "الشروط المطلوبة",
    conditionsLabel: "شروط الاستخدام",
    unavailableDatesLabel: "التواريخ غير المتاحة:",
    editionLabel: "نسخة",
    toWord: "إلى",
    todayPreset: "اليوم",
    tomorrowPreset: "غداً",
    weekendPreset: "نهاية الأسبوع",
    nextWeekPreset: "الأسبوع المقبل",
    transmissionLabel: "ناقل الحركة",
    fuelLabel: "الوقود",
    ccLabel: "حجم المحرك (cc)",
    horsepowerLabel: "القوة الحصانية",
    helmetIncludedLabel: "خوذة مجانية",
    lifeJacketsIncludedLabel: "سترات النجاة",
    automatic: "أوتوماتيكي",
    manual: "يدوي",
    petrol: "بنزين",
    diesel: "ديزل",
    electric: "كهربائي",
    hybrid: "هجين",
    yes: "نعم",
    no: "لا",
    summaryStep: "الملخص",
    addonsStep: "الإضافات",
    detailsStep: "التفاصيل",
    confirmStep: "تأكيد الحجز",
    backToVehicle: "العودة للمركبة",
    estimatedTotal: "الإجمالي المتوقع",
    yourInformation: "معلوماتك الشخصية",
    driverNameLabel: "الاسم الكامل",
    driverNamePlaceholder: "اسمك الكامل",
    fullNamePlaceholder: "اسمك الكامل",
    payOnPickupDesc: "الدفع عند الاستلام — بدون رسوم الآن",
    processing: "جاري المعالجة...",
    confirmBooking: "تأكيد حجزي",
    rateLabel: "السعر",
    durationLabel: "المدة",
    baseRentalLabel: "الإيجار الأساسي",
    quickReservation: "حجز سريع",
    selectPickupLocation: "يرجى تحديد مكان الاستلام",
    returnDateAfterPickup: "تاريخ الإرجاع يجب أن يكون بعد تاريخ الاستلام",
    bookingSuccess: "تم الحجز بنجاح! سنتصل بك قريباً.",
    premiumSelection: "تشكيلة مميزة",
    flatRateTrip: "سعر ثابت للرحلة كاملة",
    pricedPerUnit: "سعر لكل وحدة زمنية",
    pricedPerDurationUnit: "سعر لكل وحدة زمنية",
    free: "مجاني",
    noAddonsAvailable: "لا توجد خيارات إضافية متاحة لهذه المركبة.",
    secureBookingInfo: "حجز آمن",
    payOnPickupInfo: "الدفع عند الاستلام",
    dataSafeProtected: "بياناتك آمنة ومحمية",
    allSet: "تم كل شيء بنجاح!",
    hoursCountUnit: "ساعات",
    hourCountUnit: "ساعة",
    halfDaysCountUnit: "نصف يوم",
    halfDayCountUnit: "نصف يوم",
    daysCountUnit: "أيام",
    dayCountUnit: "يوم",
    car: "سيارة",
    motorcycle: "دراجة نارية",
    jetski: "جيت سكي",
    securityDepositLabel: "مبلغ الضمان (الكفالة - اختياري)",
    cautionOptionalTitle: "مبلغ الضمان (الكفالة) - اختياري",
    cautionOptionalDesc: "مبلغ مسترد بالكامل عند إرجاع المركبة بحالة جيدة",
    optional: "خيار اختياري",
    payOnPickup: "إدارة مبلغ الضمان في موقع الوكالة",
    standardCautionNotice: "دفع الوديعة مباشرة عند استلام المركبة",
    includeCautionInBooking: "تسجيل مبلغ الضمان في الحجز",
    refundable: "مستردة",
    cautionRegistered: "تم تسجيل الضمان",
    cautionPayableOnSite: "الضمان يدفع في الموقع",
    cautionRequired: "خيار دفع مبلغ الضمان اختياري",
    rentalRules: "شروط وقوانين الإيجار",
    cautionRefundableDesc: "مستردة بالكامل عند إرجاع المركبة بدون أضرار.",
    driverQuestion: "هل تحتاج إلى سائق محترف؟",
    driverPrompt: "سائق محترف (Chauffeur)",
    selfDrive: "بدون سائق (قيادة ذاتية)",
    withChauffeur: "مع سائق محترف",
    driverPriceInfo: "استعن بسائق محلي لتفادي زحام حركة المرور بسهولة",
    driverOptionLabel: "خيارات خدمة السائق",
    driverEnabled: "خدمة السائق متوفرة",
    driverDisabled: "قيادة ذاتية فقط",
    editVehicleTranslations: "إدارة التراجم",
    requirementsFr: "الشروط (فرنسية)",
    requirementsAr: "الشروط (عربية)",
    conditionsFr: "شروط أخرى (فرنسية)",
    conditionsAr: "شروط أخرى (عربية)",
    descriptionFr: "الوصف (فرنسية)",
    descriptionAr: "الوصف (عربية)",
    extraOptionsTitle: "الخيارات والإضافات الإضافية",
    extraOptionsSubtitle: "إدارة الإضافات القابلة للاستئجار مثل GPS، الخوذات، أو مقاعد الأطفال.",
    addNewOption: "إضافة خيار جديد",
    optionName: "اسم الخيار",
    price: "السعر",
    bindingRule: "قاعدة التعيين",
    actions: "إجراءات",
    globalAll: "عام (جميع المركبات)",
    categoryRule: "فئة محددة",
    vehicleRule: "مركبة محددة",
    flatRateLabel: "سعر ثابت (لكل رحلة)",
    pricedPerDay: "باليوم / وحدة الإيجار",
    editOption: "تعديل الخيار",
    newExtraOption: "خيار إضافي جديد",
    optionNameEn: "اسم الخيار (إنجليزية)",
    nameFr: "الاسم (فرنسية)",
    nameAr: "الاسم (عربية)",
    priceDa: "السعر (د.ج)",
    priceType: "نوع السعر",
    adminSelectCategory: "اختر الفئة",
    adminSelectVehicle: "اختر المركبة",
    chooseVehicle: "-- اختر مركبة --",
    saveOption: "حفظ الخيار",
    noExtraOptionsFound: "لم يتم العثور على خيارات إضافية",
    loadingOptions: "جاري تحميل الخيارات...",
    extraOptions: "الخيارات والإضافات",
    revenueTrendTitle: "تطور الإيرادات والحجوزات",
    revenueTrendSubtitle: "نظرة عامة شهرية على أداء المنصة",
    generalSettings: "الإعدادات العامة",
    heroAndBranding: "الواجهة والعلامة التجارية",
    aboutUsTab: "من نحن (قصتنا)",
    agencyLocationsTab: "فروع الوكالة",
    generalConfiguration: "الإعدادات الأساسية",
    storeName: "اسم الوكالة",
    globalAgencyPhone: "رقم الهاتف الرئيسي",
    globalAgencyEmail: "البريد الإلكتروني الرئيسي",
    globalAgencyAddress: "العنوان الرئيسي",
    storeLogo: "شعار الوكالة",
    removeLogo: "حذف الشعار",
    brandColors: "ألوان العلامة التجارية",
    preview: "معاينة",
    primaryColor: "اللون الرئيسي",
    secondaryColor: "اللون الثانوي",
    showSearchWidget: "عرض مربع البحث",
    showSearchWidgetDesc: "تمكين أو تعطيل مربع البحث بالكامل في الصفحة الرئيسية."
  }
}; */

type LanguageContextType = {
  locale: Language;
  setLocale: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
  formatCurrency: (amount: number) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const locale: Language = 'fr';

  useEffect(() => {
    document.documentElement.dir = 'ltr';
    document.documentElement.lang = 'fr';
  }, []);

  const setLocale = () => {};

  const { settings } = useSettings();

  const t = (key: string, fallback?: string): string => {
    const found = translations.fr?.[key];
    const text = found !== undefined ? found : (fallback !== undefined ? fallback : key);
    if (settings?.storeName && typeof text === 'string') {
      return text.replace(/LuxeRent/g, settings.storeName);
    }
    return text;
  };

  const formatCurrency = (amount: number): string => {
    const formatted = amount.toLocaleString('fr-DZ');
    return `${formatted} DA`;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, formatCurrency }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
